#!/bin/sh
STOW_FLAGS="-v --ignore=.preinstall"

print_usage () {
	echo \
"usage: $0 <subcommand>

SUBCOMMANDS
  install <package>    links a package
  remove  <package>    unlinks a package\
"
}

log() {
	printf "\033[90m\033[1m>> %s\033[0m\n" "$1"
}

install() {
	log "installing $1..."

	log "running preinstall script"
	preinstall="$1/.preinstall"
	[ -f "$preinstall" ] && "$preinstall"

	log "linking files"
	stow $STOW_FLAGS "$1"
	log "done"
}

remove() {
	log "removing $1..."
	stow $STOW_FLAGS -D "$1"
	log "done"
}

case "$1" in
	install)
		shift
		for pkg in "$@"; do
			install $pkg
		done
		;;
	remove) remove $2;;
	*) print_usage
esac
